<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>CBS VENTURES | Welcome</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="css/style.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="css/coin-slider.css" />
<script type="text/javascript" src="js/cufon-yui.js"></script>
<script type="text/javascript" src="js/cufon-titillium-250.js"></script>
<script type="text/javascript" src="js/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="js/script.js"></script>
<script type="text/javascript" src="js/coin-slider.min.js"></script>
</head>
<body>
<div class="main">
  <div class="header">
    <div class="header_resize">
      <div class="logo">
        <h1><img src="images/cbs.jpg" width="222" height="114" /><a href="index.html">CBS <span>VENTURES</span></a></h1>
      </div>
      <div class="searchform">
        <form id="formsearch" name="formsearch" method="post" action="#">
          <span>
          <input name="editbox_search" class="editbox_search" id="editbox_search" maxlength="80" value="Search our ste:" type="text" />
          </span>
          <input name="button_search" src="images/search.gif" class="button_search" type="image" />
        </form>
      </div>
      <div class="clr"></div>
      <div class="menu_nav">
        <ul>
          <li class="active"><a href="index.html"><span>About Us</span></a></li>
          <li><a href="service.html"><span>Services</span></a></li>
          <li><a href="product.html"><span>Product</span></a></li>
          <li><a href="support.html"><span>Support</span></a></li>
          <li><a href="contact.html"><span>Contact Us</span></a></li>
        </ul>
      </div>
      <div class="clr"></div>
      <div class="slider">
        <div id="coin-slider"> <a href="#"><img src="images/advancement-of-technology.jpg" width="960" height="320" alt="" /><span><big>At CBS Ventures we measure our achievement by the success of our clients.</big><br />
          We help organizations define and achieve strategic objectives through the effective application of appropriate information technology.
 This often means introducing new business processes using advances in the technologies implemented.</span></a> <a href="#"><img src="images/technology.jpg" width="960" height="320" alt="" /><span><big>CBS Ventures consultant work closely with clients</big><br />
          frequently among the dominant players in their respective industries o leverage the potential of technology for practical business advantage and improve services to customer and stakeholders to increase profitability, productivity and market share, among other goals.o leverage the potential of technology for practical business advantage and improve services to customer and stakeholders to increase profitability, productivity and market share, among other goals.</span></a> <a href="#"><img src="images/computer.jpg" width="960" height="320" alt="" /><span><big>We rely on a combination of management consulting skills.</big><br />
        in depth knowledge of relevant technologies and familiarity with the industries our clients operate and compete in to develop and deliver solutions for our clients.Virtually all work at CBS Ventures is carried out by teams comprised of people with diverse experiences, backgrounds and skills.</span></a> </div>
        <div class="clr"></div>
      </div>
      <div class="clr"></div>
    </div>
  </div>
  <div class="content">
    <div class="content_resize">
      <div class="mainbar">
        <div class="article">
          <h2>WELCOME</h2>
          <p></p>
          <div class="clr"></div>
          <div class="img"></div>
          <div class="post_content">
            <p>Creative Business Ventures Sdn. Bhd. (formerly known as Squadra Enterprise Sdn. Bhd.) was incorporated on 19 September 2002 under the Companies  Act, 1965. In line with government's objective of promoting the k-economy, the company made a strategic decision to focus its resources in the ICT sector, but nonrtheless we are also involved in diversified business such as M & E maintenance , seminars and others due to the fact that our key personal having different background.</p>
            <p>Creative Business Ventures Sdn. Bhd. Consultant work closely with clients – frequently among the dominant players in their respective industries  - to leverage the potential ofm technology for practical business advantage and impove services to customers and stakeholder to increase profitability, productivity and market share, among other goals. This often means introducing new business processes using advances in the technologies implemented.</p><p>We rely on combination of management consulting skills, in depth knowledge of relevant technologies and familiarity with the industries our clients operate and compete in to develop and deliver solutions for our clients. Virtually all work at Creative Business Ventures Sdn. Bhd. Is carried out by teams comprised of people with diverse experiences, backgrounds and skills.

WCreative Business Ventures Sdn. Bhd. Firmly believbes that, armed with its experience, expertise and commitment it can deliver solutions to satisfy the client's needs in order to meet its corporate objectives.</p>
            <p class="spec"><a href="#" class="rm"></a></p>
          </div>
          <div class="clr"></div>
        </div>
        
        <p class="pages"><small>Page 1 of 2</small> <span>1</span> <a href="#">2</a> <a href="service.html">&raquo;</a></p>
      </div>
      <div class="sidebar">
        <div class="gadget">
          <h2 class="star">Menu</h2>
          <div class="clr"></div>
          <ul class="sb_menu">
            <li><a href="index.html">About Us</a></li>
            <li><a href="service.html">Services</a></li>
            <li><a href="product.html">Product</a></li>
            <li><a href="support.html">Support</a></li>
            <li><a href="contact.html">Contact Us</a></li>
            
          </ul>
        </div>
        <div class="gadget">
          <h2 class="star"><span>Link</span></h2>
          <div class="clr"></div>
          <ul class="ex_menu">
            <li><a href="http://www.skm.gov.my//">SKM</a><br />
              Suruhanjaya Koperasi Malaysia</li>
            <li><a href="http://www.kpkk.gov.my/">KPKK</a><br />
              Kementerian Penerangan Komunikasi dan Kebudayaan</li>
            <li><a href="https://www.eperolehan.com.my/">E PEROLEHAN</a><br />
              Laman Rasmi eperolehan</li>
            <li><a href="http://www.1pengguna.com/">1 PENGGUNA</a><br />
              Portal Pengguna Bijak</li>
            <li><a href="http://kpwkm.gov.my/">KPWKM</a><br />
              Kementerian Pembangunan Wanita, Keluarga dan Masyarakat.</li>
            <li><a href="http://kpdnkk.gov.my/">KPDNKK</a><br />
              Kementerian Perdagangan Dalam Negeri, Koperasi dan Kepenggunaan</li>
          </ul>
        </div>
      </div>
      <div class="clr"></div>
    </div>
  </div>
  <div class="fbg">
    <div class="fbg_resize">
      <div class="col c1">
        <h2><span>Image</span> Gallery</h2>
        <a href="#"><img src="images/ITb75.jpg" width="75" height="75" alt="" class="gal" /></a> <a href="#"><img src="images/dek75.jpg" width="75" height="75" alt="" class="gal" /></a> <a href="#"><img src="images/sw300-75.jpg" width="75" height="75" alt="" class="gal" /></a> <a href="#"><img src="images/Comp_Repair75.jpg" width="75" height="75" alt="" class="gal" /></a> <a href="#"><img src="images/istock-75.jpg" width="75" height="75" alt="" class="gal" /></a> <a href="#"><img src="images/WinmodemAndRegularModem1-75.jpg" width="75" height="75" alt="" class="gal" /></a> </div>
      <div class="col c2">
        <h2><span>Services</span> Overview</h2>
        <p>We create new applications as well as redesign legacy software.Our priorities are our customer's satisfaction, application of new technologies and delivery on time and as per budget.This short list demonstrates a general outline of our services for various business branches:</p>
        <ul class=>
          <li>Web Design Solutions & Hosting.</li>
          <li>ICT Consultancy Services.</li>
          <li>System Applications Development.</li>
        </ul>
      </div>
      <div class="col c3">
        <h2><span>Contact</span> Us</h2>
        <p>CREATIVE BUSINESS VENTURES SDN. BHD.</p>
        <p class="contact_info"> <span>Address:</span> No.79 -2 Platinum Walks, 2 Jalan Langkawi, 53300 Setapak, Kuala Lumpur.<br />
          <span>Telephone:</span> +603 4256 4526<br />
          <span>FAX:</span> +603 4257 4526<br />
          <span>Others:</span> +012 - 358 - 2525<br />
          <span>E-mail:</span> <a href="contact.html">info@cbsventures.com.my</a> </p>
      </div>
      <div class="clr"></div>
    </div>
  </div>
  <div class="footer">
    <div class="footer_resize">
      <p class="lf">&copy; Copyright <a href="#">CBS Ventures</a>.</p>
      <p class="rf">Design by Ezek <a href="http://www.ezek.allalla.com/">Web Designer</a></p>
      <div style="clear:both;"></div>
    </div>
  </div>
</div>
</body>
</html>
